In [54]:
revenus = [1800, 1500, 2200, 3000, 2172]

print(revenus)

[1800, 1500, 2200, 3000, 2172]


In [55]:
#Calcul de la moyenne de facon normal (ancienne version avant numpy)

def moyenne(liste):
    return sum(liste)/len(liste)
moyenne(revenus)  #2134.4


2134.4

In [56]:
import numpy as np
import pandas as pd

In [57]:
np.mean(revenus)

2134.4

In [58]:
x = [-2, -1, 1, 2]
print("La valeurs absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print('Logarithme: ', np.log(np.abs(x)))

La valeurs absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [59]:
revenus_array = np.array(revenus)
revenus_array

array([1800, 1500, 2200, 3000, 2172])

In [60]:
tableau_zero = np.zeros(len(revenus))
tableau_zero

array([0., 0., 0., 0., 0.])

In [61]:
y = [1, 3, 10]
tableau_1 = np.zeros(y)
tableau_1

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [62]:
tableau_2 = np.ones(y)
print('tableau_2', tableau_2)
tableau_3 = np.arange(1, 8, 2)
print('tableau_3', tableau_3)
tableau_4 = np.linspace(5, 10, 11)
print('tableau_4', tableau_4)

tableau_2 [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
tableau_3 [1 3 5 7]
tableau_4 [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]


In [63]:
print(tableau_4.dtype)
print(revenus_array.dtype)

float64
int64


In [64]:
print(revenus_array)
print(revenus_array[0]) #premier element de la table revenus_array, index 0
print(revenus_array[1])
print(revenus_array[2])
print(revenus_array[3])
print(revenus_array[4])

print(revenus_array[-1]) #dernier élèment de la table index -1
print(revenus_array[2:4]) #les élèments situés entre l'index 2 et 4 (le 4 est toujours exclu)
print(revenus_array[:3]) #tout les éléments jusqu'à l'index 3 (exclus)
print(revenus_array[3:]) #tout les éléments jusqu'à la fin
print(revenus_array[::3]) #tou les élements en commencant par le premier avec un pas de 3
print(revenus_array[2::]) #même chose que [3:] mais plus précis


[1800 1500 2200 3000 2172]
1800
1500
2200
3000
2172
2172
[2200 3000]
[1800 1500 2200]
[3000 2172]
[1800 3000]
[2200 3000 2172]


In [65]:
revenus_array[4] = 2172
revenus_array


array([1800, 1500, 2200, 3000, 2172])

In [66]:
print('premiere condition', revenus_array[revenus_array > 2000])


print('deuxieme condition', revenus_array[(revenus_array > 2000) & (revenus_array < 3000)])

revenus_array[(revenus_array > 2000) & (revenus_array < 2180)] = 2172
revenus_array


premiere condition [2200 3000 2172]
deuxieme condition [2200 2172]


array([1800, 1500, 2200, 3000, 2172])

In [67]:
print('moyenne', revenus_array.mean())
print('shape', revenus_array.shape) #nombre d'éléments
print('min', revenus_array.min())
print('max', revenus_array.max())
print('base', revenus_array.base) 
print('sum', revenus_array.sum()) #somme
print('argmin', revenus_array.argmin())
print('argmax', revenus_array.argmax())#donne l'index de la plus grande valeur

moyenne 2134.4
shape (5,)
min 1500
max 3000
base None
sum 10672
argmin 1
argmax 3


In [68]:
revenus_array.sort()
print(revenus_array.sort())

None


Transformez vos données en tableaux

In [69]:
hugo = [21, 1400, 0]
richard = [54, 2800, 2]
emilie = [27, 3700, 3]

tableur = [hugo, richard, emilie]
tableur1 = np.array(tableur)
tableur1

array([[  21, 1400,    0],
       [  54, 2800,    2],
       [  27, 3700,    3]])

In [70]:
np.ones((3,2))
np.ones((2, 3))
np.random.random((4,3))
np.random.randint(2, 20, size=(3,4))

array([[16,  6, 10, 17],
       [18,  2, 19, 13],
       [ 4, 15, 14, 18]])

In [71]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])
C = np.array([[2, 4, 6], [8, 10, 12]])

In [72]:
import pandas as pd

In [73]:
dispo_alimentaire_test = pd.read_csv('../Source/dispo_alimentaire_test.csv')
dispo_alimentaire_test

Zone                Produit   Origine  Aliments pour animaux  \
0       Afghanistan       Abats Comestible   animale                    NaN   
1       Afghanistan        Agrumes, Autres  vegetale                    NaN   
2       Afghanistan  Aliments pour enfants  vegetale                    NaN   
3       Afghanistan                 Ananas  vegetale                    NaN   
4       Afghanistan                Bananes  vegetale                    NaN   
...             ...                    ...       ...                    ...   
15600  Îles Salomon       Viande de Suides   animale                    NaN   
15601  Îles Salomon    Viande de Volailles   animale                    NaN   
15602  Îles Salomon          Viande, Autre   animale                    NaN   
15603  Îles Salomon                    Vin  vegetale                    NaN   
15604  Îles Salomon         Épices, Autres  vegetale                    NaN   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                      NaN                                             5.0   
1                      NaN                                             1.0   
2                      NaN                                             1.0   
3                      NaN                                             0.0   
4                      NaN                                             4.0   
...                    ...                                             ...   
15600                  NaN                                            45.0   
15601                  NaN                                            11.0   
15602                  NaN                                             0.0   
15603                  NaN                                             0.0   
15604                  NaN                                             4.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                   1.72        
1                                                   1.29        
2                                                   0.06        
3                                                   0.00        
4                                                   2.70        
...                                                  ...        
15600                                               4.70        
15601                                               3.34        
15602                                               0.06        
15603                                               0.07        
15604                                               0.48        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                                   0.20               
1                                                   0.01               
2                                                   0.01               
3                                                    NaN               
4                                                   0.02               
...                                                  ...               
15600                                               4.28               
15601                                               0.69               
15602                                                NaN               
15603                                                NaN               
15604                                               0.21               

       Disponibilité de protéines en quantité (g/personne/jour)  \
0                                                   0.77          
1                                                   0.02          
2                                                   0.03          
3                                                    NaN          
4                                                   0.05          
...                                                  ...          
15600         

In [74]:
sous_nutrition = pd.read_csv('../Source/sous_nutrition.csv')
sous_nutrition

Zone      Année Valeur
0     Afghanistan  2012-2014    8.6
1     Afghanistan  2013-2015    8.8
2     Afghanistan  2014-2016    8.9
3     Afghanistan  2015-2017    9.7
4     Afghanistan  2016-2018   10.5
...           ...        ...    ...
1213     Zimbabwe  2013-2015    NaN
1214     Zimbabwe  2014-2016    NaN
1215     Zimbabwe  2015-2017    NaN
1216     Zimbabwe  2016-2018    NaN
1217     Zimbabwe  2017-2019    NaN

[1218 rows x 3 columns]

In [75]:
sous_nutrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Zone    1218 non-null   object
 1   Année   1218 non-null   object
 2   Valeur  624 non-null    object
dtypes: object(3)
memory usage: 28.7+ KB


In [76]:
sous_nutrition['Valeur'] = pd.to_numeric(sous_nutrition['Valeur'],errors='coerce')
sous_nutrition.fillna(0, inplace=True)
sous_nutrition = sous_nutrition.head(12)
sous_nutrition = sous_nutrition
sous_nutrition

Zone      Année  Valeur
0      Afghanistan  2012-2014     8.6
1      Afghanistan  2013-2015     8.8
2      Afghanistan  2014-2016     8.9
3      Afghanistan  2015-2017     9.7
4      Afghanistan  2016-2018    10.5
5      Afghanistan  2017-2019    11.1
6   Afrique du Sud  2012-2014     2.2
7   Afrique du Sud  2013-2015     2.5
8   Afrique du Sud  2014-2016     2.8
9   Afrique du Sud  2015-2017     3.0
10  Afrique du Sud  2016-2018     3.1
11  Afrique du Sud  2017-2019     3.3

In [77]:
sous_nutrition.loc[sous_nutrition['Année'] == '2012-2014', 'Année'] = '2013'
sous_nutrition.loc[sous_nutrition['Année'] == '2013-2015', 'Année'] = '2014'
sous_nutrition.loc[sous_nutrition['Année'] == '2014-2016', 'Année'] = '2015'
sous_nutrition.loc[sous_nutrition['Année'] == '2015-2017', 'Année'] = '2016'
sous_nutrition.loc[sous_nutrition['Année'] == '2016-2018', 'Année'] = '2017'
sous_nutrition.loc[sous_nutrition['Année'] == '2017-2019', 'Année'] = '2018'
sous_nutrition['Année'] = pd.to_numeric(sous_nutrition['Année'], errors='coerce')
sous_nutrition = sous_nutrition
sous_nutrition


/var/folders/75/1ffttkv52sv3447dlb59t6nc0000gn/T/ipykernel_77259/1005978164.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sous_nutrition['Année'] = pd.to_numeric(sous_nutrition['Année'], errors='coerce')


Zone  Année  Valeur
0      Afghanistan   2013     8.6
1      Afghanistan   2014     8.8
2      Afghanistan   2015     8.9
3      Afghanistan   2016     9.7
4      Afghanistan   2017    10.5
5      Afghanistan   2018    11.1
6   Afrique du Sud   2013     2.2
7   Afrique du Sud   2014     2.5
8   Afrique du Sud   2015     2.8
9   Afrique du Sud   2016     3.0
10  Afrique du Sud   2017     3.1
11  Afrique du Sud   2018     3.3

for index in sous_nutrition.index:
    print(sous_nutrition['Valeur'][index],
        sous_nutrition['Année'][index])

In [78]:
for rows in sous_nutrition.itertuples():
    print(getattr(rows, 'Valeur')/getattr(rows, 'Année'))

0.0042722305017386985
0.004369414101290964
0.004416873449131514
0.004811507936507936
0.005205751115518097
0.005500495540138751
0.001092896174863388
0.0012413108242303873
0.0013895781637717122
0.001488095238095238
0.0015369360436291522
0.0016352824578790882


In [79]:
sous_nutrition = sous_nutrition.pivot_table(values='Valeur', index='Zone', columns='Année')
sous_nutrition

Année           2013  2014  2015  2016  2017  2018
Zone                                              
Afghanistan      8.6   8.8   8.9   9.7  10.5  11.1
Afrique du Sud   2.2   2.5   2.8   3.0   3.1   3.3

In [80]:
liste = ['putain','ishem','tu','fais','chier','fort']

In [81]:
liste

['putain', 'ishem', 'tu', 'fais', 'chier', 'fort']

In [82]:
liste[1] = 'Tom'

In [83]:
liste

['putain', 'Tom', 'tu', 'fais', 'chier', 'fort']

In [84]:
liste.append('Hello')
liste

['putain', 'Tom', 'tu', 'fais', 'chier', 'fort', 'Hello']

In [85]:
liste.remove(liste[3])
liste

['putain', 'Tom', 'tu', 'chier', 'fort', 'Hello']

In [86]:
liste.remove('Tom')

In [87]:
liste

['putain', 'tu', 'chier', 'fort', 'Hello']

In [88]:
len(liste)

5

In [89]:
liste.sort()
liste

['Hello', 'chier', 'fort', 'putain', 'tu']

In [90]:
liste.sort()
liste.reverse()
liste

['tu', 'putain', 'fort', 'chier', 'Hello']

In [91]:
liste.append("putain")
liste.count('putain')

2

In [92]:
liste.extend(['salut', 'ca', 'va'])

In [93]:
liste

['tu', 'putain', 'fort', 'chier', 'Hello', 'putain', 'salut', 'ca', 'va']

In [94]:
liste.insert(2, 'hello')
liste

['tu',
 'putain',
 'hello',
 'fort',
 'chier',
 'Hello',
 'putain',
 'salut',
 'ca',
 'va']

In [95]:
liste.pop()

'va'

In [96]:
liste.append('fais')
liste.extend(['putain', 'putain', 'fais', 'fais'])
liste

['tu',
 'putain',
 'hello',
 'fort',
 'chier',
 'Hello',
 'putain',
 'salut',
 'ca',
 'fais',
 'putain',
 'putain',
 'fais',
 'fais']

In [97]:
liste.index('putain')

1

In [98]:
alpha = ('tu', 'putain',
 'hello',
 'fort',
 'chier',
 'Hello',
 'putain',
 'salut',
 'ca',
 'fais',
 'fais',
 'putain',
 'putain',
 'fais',
 'fais')

In [99]:
alpha

('tu',
 'putain',
 'hello',
 'fort',
 'chier',
 'Hello',
 'putain',
 'salut',
 'ca',
 'fais',
 'fais',
 'putain',
 'putain',
 'fais',
 'fais')

In [100]:
alpha.count('putain')


4

In [101]:
resultat = [i for i in range(10)]
print(resultat)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [102]:
lol = 100
bin(lol)

'0b1100100'

In [103]:
oct(0)

'0o0'

In [1]:
import numpy as np

In [6]:
import pandas as pd
#import Projet4_Final.py
import importlib

#get_dataframe = importlib.import_module('Projet4_Final.ipynb').get_dataframe()
get_dataframe()

NameError: name 'get_dataframe' is not defined

In [13]:
data = pd.read_csv("../Source/FAOSTAT_data.csv")

sous_nutrition = pd.read_csv("../Source/dispo_alimentaire.csv")
sous_nutrition



Zone                Produit   Origine  Aliments pour animaux  \
0       Afghanistan       Abats Comestible   animale                    NaN   
1       Afghanistan        Agrumes, Autres  vegetale                    NaN   
2       Afghanistan  Aliments pour enfants  vegetale                    NaN   
3       Afghanistan                 Ananas  vegetale                    NaN   
4       Afghanistan                Bananes  vegetale                    NaN   
...             ...                    ...       ...                    ...   
15600  Îles Salomon       Viande de Suides   animale                    NaN   
15601  Îles Salomon    Viande de Volailles   animale                    NaN   
15602  Îles Salomon          Viande, Autre   animale                    NaN   
15603  Îles Salomon                    Vin  vegetale                    NaN   
15604  Îles Salomon         Épices, Autres  vegetale                    NaN   

       Autres Utilisations  Disponibilité alimentaire (Kcal/personne/jour)  \
0                      NaN                                             5.0   
1                      NaN                                             1.0   
2                      NaN                                             1.0   
3                      NaN                                             0.0   
4                      NaN                                             4.0   
...                    ...                                             ...   
15600                  NaN                                            45.0   
15601                  NaN                                            11.0   
15602                  NaN                                             0.0   
15603                  NaN                                             0.0   
15604                  NaN                                             4.0   

       Disponibilité alimentaire en quantité (kg/personne/an)  \
0                                                   1.72        
1                                                   1.29        
2                                                   0.06        
3                                                   0.00        
4                                                   2.70        
...                                                  ...        
15600                                               4.70        
15601                                               3.34        
15602                                               0.06        
15603                                               0.07        
15604                                               0.48        

       Disponibilité de matière grasse en quantité (g/personne/jour)  \
0                                                   0.20               
1                                                   0.01               
2                                                   0.01               
3                                                    NaN               
4                                                   0.02               
...                                                  ...               
15600                                               4.28               
15601                                               0.69               
15602                                                NaN               
15603                                                NaN               
15604                                               0.21               

       Disponibilité de protéines en quantité (g/personne/jour)  \
0                                                   0.77          
1                                                   0.02          
2                                                   0.03          
3                                                    NaN          
4                                                   0.05          
...                                                  ...          
15600         